// <auto-generated />
using System;
using CodeSnippets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeSnippets.Infrastructure.Migrations.SqliteEF
{
    [DbContext(typeof(SqliteEFContext))]
    partial class SqliteEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CodeSnippets.Infrastructure.Entities.SampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("BoolValue");

                    b.Property<DateTime>("DateTimeValue");

                    b.Property<string>("StringValue");

                    b.HasKey("Id");

                    b.ToTable("SampleEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
