// <auto-generated />
using System;
using CodeSnippets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CodeSnippets.Infrastructure.Migrations
{
    [DbContext(typeof(NpgsqlEFContext))]
    [Migration("20190826082740_InitializeCreate")]
    partial class InitializeCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CodeSnippets.Infrastructure.Entities.Blog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("CodeSnippets.Infrastructure.Entities.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Blogid");

                    b.Property<int>("blog_Id");

                    b.Property<string>("content");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.HasIndex("Blogid");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("CodeSnippets.Infrastructure.Entities.Post", b =>
                {
                    b.HasOne("CodeSnippets.Infrastructure.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("Blogid");
                });
#pragma warning restore 612, 618
        }
    }
}
